---
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${TAG}
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${TAG}
    ports: ['127.0.0.1:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${TAG}
    networks: ['stack']
    depends_on: ['elasticsearch']

  setup_heartbeat:
    image: docker.elastic.co/beats/heartbeat:${TAG}
    volumes: ['./scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro']
    command: /usr/local/bin/setup-beat.sh heartbeat
    environment:
      SLEEP_TIME: ${SLEEP_TIME}
    networks: ['stack']
    depends_on: ['kibana']

networks: {stack: {}}
